version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: ai_analyzer_postgres
    restart: always
    environment:
      POSTGRES_USER: rain9_ai_data
      POSTGRES_PASSWORD: rain9_ai_data_admin
      POSTGRES_DB: ai_analysis_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
